services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - "$SERVER_IP:$ACTUAL_PORT:5006"
    volumes:
      - ../volumes/actual/actual-data:/data
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
